# Generated by Django 5.0.7 on 2025-06-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_cartao', to='core.conta'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro/Conta'), ('cartao_credito_avista', 'Cartão de Crédito (à vista)'), ('cartao_credito_parcelado', 'Cartão de Crédito (parcelado)')], default='dinheiro', max_length=30),
        ),
    ]
