# Generated by Django 5.0.7 on 2025-06-29 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_despesa_cartao_despesa_parcelas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, help_text='Apenas os 4 últimos dígitos', max_length=20)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('diners', 'Diners Club'), ('outros', 'Outros')], default='visa', max_length=20)),
                ('titular', models.CharField(max_length=100)),
                ('data_vencimento_fatura', models.PositiveSmallIntegerField(help_text='Dia do vencimento da fatura')),
                ('data_fechamento_fatura', models.PositiveSmallIntegerField(help_text='Dia do fechamento da fatura')),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chave_seguranca', models.CharField(blank=True, help_text='CVV, não exibir em tela', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_pagamento', to='core.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario', 'numero')},
            },
        ),
    ]
