# Generated by Django 5.0.7 on 2025-06-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartaocredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_cartao', to='core.cartaocredito'),
        ),
    ]
