# Generated by Django 5.0.7 on 2025-06-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_despesa_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_dragdrop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_layout',
            field=models.CharField(choices=[('default', 'Padrão'), ('compact', 'Compacto'), ('wide', 'Amplo'), ('tall', 'Alto')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_refresh',
            field=models.PositiveIntegerField(default=5, help_text='Intervalo de atualização automática (minutos)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_tema',
            field=models.CharField(choices=[('default', 'Padrão'), ('dark', 'Escuro'), ('light', 'Claro'), ('colorful', 'Colorido')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dashboard_tipo',
            field=models.CharField(choices=[('moderno', 'Moderno'), ('classico', 'Clássico')], default='moderno', max_length=20),
        ),
    ]
