# Generated by Django 5.0.7 on 2025-07-01 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_fatura', to='core.fatura'),
        ),
    ]
